"""
11;rgb:0000/0000/0000Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v)$9sw6iseu-c!!a7ck5g8z1-s4^nr(5yl$=*&-qfe)j9n@!9r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# XSS protection
SECURE_BROWSER_XSS_FILTER = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Prevent content type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Secure cookies
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Optionally, force HTTPS (if running on production)
SECURE_SSL_REDIRECT = True  # redirect HTTP → HTTPS

ALLOWED_HOSTS = []

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# HTTP Strict Transport Security (HSTS)
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Security headers
X_FRAME_OPTIONS = 'DENY'               # Prevent clickjacking
SECURE_CONTENT_TYPE_NOSNIFF = True     # Prevent content-type sniffing
SECURE_BROWSER_XSS_FILTER = True       # Enable browser XSS filter

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',  # if using django-csp
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Content Security Policy
CSP_DEFAULT_SRC = ("'self'",)  # Only allow content from your own domain
CSP_STYLE_SRC = ("'self'", 'fonts.googleapis.com')  # Allow Google Fonts
CSP_SCRIPT_SRC = ("'self'", 'ajax.googleapis.com')  # Allow scripts from your domain + Google Ajax




AUTH_USER_MODEL = 'bookshelf.CustomUser'
# AUTH_USER_MODEL = 'relationship_app.UserProfile'



ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'





# SECURITY MEASURES IMPLEMENTED
# 1. DEBUG=False → hide detailed errors in production
# 2. SECURE_BROWSER_XSS_FILTER=True → protect against XSS attacks
# 3. X_FRAME_OPTIONS='DENY' → prevent clickjacking
# 4. SECURE_CONTENT_TYPE_NOSNIFF=True → prevent MIME type sniffing
# 5. CSRF_COOKIE_SECURE=True → CSRF cookies only over HTTPS
# 6. SESSION_COOKIE_SECURE=True → session cookies only over HTTPS
# 7. All forms use {% csrf_token %} to prevent CSRF attacks
# 8. ORM queries used to prevent SQL injection

